version: "3.8"
services:

        php:
            build:
                context: symfony
                args:
                    SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                    STABILITY: ${STABILITY:-stable}
            restart: unless-stopped
            healthcheck:
                interval: 10s
                timeout: 3s
                retries: 3
                start_period: 30s
                


        db:
            image: mysql:8.0.31
            container_name: db_docker_symfony
            restart: always
            volumes:
                - db-data:/var/lib/mysql
            environment:
                MYSQL_DATABASE: 'db'
                MYSQL_USER: 'root'
                MYSQL_PASSWORD: '123'
                MYSQL_ROOT_PASSWORD: '123'
            ports:
                - "6033:8082"
        
        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: pma
            links:
                - db
            environment:
                PMA_HOST: 'db'
                PMA_PORT: 8082
                PMA_ARBITRARY: 1
                PMA_USER: 'root'
                PMA_PASSWORD: '1234'
            restart: always
            ports:
                - 8081:80
        apache:
            image: httpd:2.4.54
            container_name: my-apache-app
            ports:
                - '8085:80'
            volumes:
                - ./website:/usr/local/apache2/htdocs



        maildev:
            image: maildev/maildev
            restart: always
            environment:
                - TZ=Europe/Paris
                - MAILDEV_WEB_PORT=1080
                - MAILDEV_SMTP_PORT=1025
            ports:
                - "8080:1080"
                - "8025:1025"
volumes:
  db-data: 
  